version: '2'
services:
  influxdb:
    image: influxdb
    command: -config /etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ~/influxdb-data:/var/lib/influxdb
      - $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $PWD/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ~/mosquitto-data:/mosquitto/data
      - ~/mosquitto-log:/mosquitto/log