version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka-docker
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.123.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-javaagent:/opt/kafka/prometheus/prometheus.jar=7071:/opt/kafka/prometheus/kafka.yml"
    volumes:
      - $PWD/prometheus:/opt/kafka/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/kafka-data:/tmp/kafka-logs
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/grafana-data:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    command: --config.file=/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus/prometheus.yml:/prometheus.yml
      - ~/prometheus-data:/prometheus-data